"""Evaluator agent — judges the answerer agent's answer for correctness and completeness."""

from pathlib import Path

from langchain_core.language_models import BaseChatModel
from langchain_core.tools import BaseTool, tool
from pydantic import BaseModel, Field

EVALUATOR_PROMPT_PATH = Path(__file__).parent.parent / "prompts" / "evaluator.md"


def _load_evaluator_prompt() -> str:
    return EVALUATOR_PROMPT_PATH.read_text(encoding="utf-8")


class RubricScores(BaseModel):
    """Per-criterion rubric scores (0–3 each).

    Scoring guide
    ------------
    correctness  : 0 = critical medical errors, 1 = mostly wrong,
                   2 = mostly correct with minor inaccuracies, 3 = fully correct
    completeness : 0 = missing everything, 1 = partially addresses question,
                   2 = mostly complete, 3 = fully addresses all aspects
    evidence_alignment : 0 = no connection to vignette, 1 = vague/weak connection,
                        2 = moderate explicit connection, 3 = strong explicit link
    distractor_elimination : 0 = ignores distractors, 1 = mentions but unclear,
                             2 = good comparison, 3 = excellent why-chosen > why-not
    """

    correctness: int = Field(..., ge=0, le=3, description="Medical accuracy score (0-3)")
    completeness: int = Field(..., ge=0, le=3, description="Addresses all question aspects (0-3)")
    evidence_alignment: int = Field(
        ..., ge=0, le=3, description="Explicitly links vignette findings to answer (0-3)"
    )
    distractor_elimination: int = Field(
        ..., ge=0, le=3, description="Explains why chosen option beats distractors (0-3)"
    )


class EvaluationResult(BaseModel):
    """Structured output schema for the evaluator agent with rubric scoring."""

    # Per-criterion scores
    correctness: int = Field(..., ge=0, le=3)
    completeness: int = Field(..., ge=0, le=3)
    evidence_alignment: int = Field(..., ge=0, le=3)
    distractor_elimination: int = Field(..., ge=0, le=3)

    # Derived overall verdict (must agree with rubric)
    verdict: str  # "correct" | "incorrect" | "incomplete"
    reasoning: str  # per-criterion explanation (which criterion failed and why)
    evaluator_confidence: float = Field(
        ..., ge=0.0, le=1.0,
        description="How confident the evaluator is in this judgment (0.0-1.0)"
    )


def create_evaluator_agent(
    model: BaseChatModel,
    tools: list[BaseTool] | None = None,
) -> BaseTool:
    """Create the evaluator agent tool.

    Args:
        model: The shared chat model to use for all agents.
        tools: Ignored (present for API compatibility with future multi-tool agents).

    Returns:
        An ``evaluate_answer`` tool that judges a draft answer for correctness
        and completeness against the original question and context.
    """

    @tool
    def evaluate_answer(
        draft_answer: str,
        question: str,
        context: str,
    ) -> str:
        """Evaluate whether the answerer agent's draft answer is correct and complete.

        Args:
            draft_answer: The answer generated by the answerer agent.
            question: The original MedQA-style question (multiple choice or free response).
            context: The textbook context used to generate the draft answer.

        Returns:
            A JSON string with per-criterion rubric scores (0-3 each),
            an overall "verdict", "reasoning", and "evaluator_confidence".
        """
        system_prompt = _load_evaluator_prompt()
        user_message = (
            f"Question:\n{question}\n\n"
            f"Context:\n{context}\n\n"
            f"Draft Answer:\n{draft_answer}"
        )
        response = model.with_structured_output(EvaluationResult).invoke([
            {"role": "system", "content": system_prompt},
            {"role": "user", "content": user_message},
        ])
        import json
        return json.dumps({
            "correctness": response.correctness,
            "completeness": response.completeness,
            "evidence_alignment": response.evidence_alignment,
            "distractor_elimination": response.distractor_elimination,
            "verdict": response.verdict,
            "reasoning": response.reasoning,
            "evaluator_confidence": response.evaluator_confidence,
        })

    return evaluate_answer
