"""Evaluator agent — judges the answerer agent's answer for correctness and completeness."""

from pathlib import Path

from langchain_core.language_models import BaseChatModel
from langchain_core.tools import BaseTool, tool
from pydantic import BaseModel

EVALUATOR_PROMPT_PATH = Path(__file__).parent.parent / "prompts" / "evaluator.md"


def _load_evaluator_prompt() -> str:
    return EVALUATOR_PROMPT_PATH.read_text(encoding="utf-8")


class EvaluationResult(BaseModel):
    """Structured output schema for the evaluator agent."""

    verdict: str  # "correct" | "incorrect" | "incomplete"
    reasoning: str


def create_evaluator_agent(
    model: BaseChatModel,
    tools: list[BaseTool] | None = None,
) -> BaseTool:
    """Create the evaluator agent tool.

    Args:
        model: The shared chat model to use for all agents.
        tools: Ignored (present for API compatibility with future multi-tool agents).

    Returns:
        An ``evaluate_answer`` tool that judges a draft answer for correctness
        and completeness against the original question and context.
    """

    @tool
    def evaluate_answer(draft_answer: str, question: str, context: str) -> str:
        """Evaluate whether the answerer agent's draft answer is correct and complete.

        Args:
            draft_answer: The answer generated by the answerer agent.
            question: The original MedQA-style question (multiple choice or free response).
            context: The textbook context used to generate the draft answer.

        Returns:
            A JSON string with "verdict" ("correct" | "incorrect" | "incomplete")
            and "reasoning" explaining the verdict.
        """
        system_prompt = _load_evaluator_prompt()
        user_message = (
            f"Question:\n{question}\n\n"
            f"Context:\n{context}\n\n"
            f"Draft Answer:\n{draft_answer}"
        )
        response = model.with_structured_output(EvaluationResult).invoke([
            {"role": "system", "content": system_prompt},
            {"role": "user", "content": user_message},
        ])
        import json
        return json.dumps({
            "verdict": response.verdict,
            "reasoning": response.reasoning,
        })

    return evaluate_answer
